# Week 02 Assignment glucose level data

Welcome to week two of this course programming 1. You will learn about time related data wrangling with pandas and you will learn to visualize with bokeh. This week will be focussed around missing data. Concretely, you will preprocess the glucose json file using interpolation to impute in order to conduct visual analysis. Learning outcomes:

- load a json dataset 
- typecast the Pandas DataFrame to appropiate data types
- inspect the dataset for quality and metadata information
- add a column with interpolated data in Pandas DataFrame
- perform visual analysis

The assignment consists of 6 parts:

- [part 1: load the data](#0)
     - [Exercise 1.1](#ex-11)
- [part 2: prepare for inspection](#1)
     - [Exercise 2.1](#ex-21)
- [part 3: inspect the data](#2)
     - [Exercise 3.1](#ex-31)
- [part 4: interpolate the data](#3)
     - [Exercise 4.1](#ex-41)
- [part 5: visualize the data](#4)
     - [Exercise 5.1](#ex-51)
- [part 6: Challenge](#5)
     - [Exercise 6.1](#ex-61)

Part 1 and 5 are mandatory, part 6 is optional (bonus)
To pass the assingnment you need to a score of 60%.

<a name='0'></a>
## Part 1: Load the data

Instructions: Load the json datafile `glucose.json` into a pandas dataframe. Check your dataframe with a `.head()` to compare with the expected outcome

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<ul><li>json.load() method reads a file, pd.read_json converts it to a Pandas DataFrame</li>
    <li>when loading into a Pandas DataFrame use records orientation </li>
</ul>
</details>

<a name='ex-11'></a>
### Code your solution

In [68]:
# CODE YOUR SOLUTION HERE
import pandas as pd
import json

with open('glucose.json', 'r') as f:
  data = json.load(f)
df = pd.read_json(data)

df.head(20)
# display(df)

        ID              time  recordtype glucose
0   2845.0  2019-04-25 00:08           1     109
1   2850.0  2019-04-25 00:50           1
2   2877.0  2019-04-25 07:02           1     123
3   2881.0  2019-04-25 07:34           1     158
4   2886.0  2019-04-25 08:19           1
5   2899.0  2019-04-25 11:01           1     139
6   2909.0  2019-04-25 13:14           1     151
7   2916.0  2019-04-25 14:17           1     129
8   2922.0  2019-04-25 14:45           1     161
9   2925.0  2019-04-25 14:55           1     184
10  2927.0  2019-04-25 14:59           1     178
11  2929.0  2019-04-25 15:00           1     178
12  2932.0  2019-04-25 15:11           1     121
13  2935.0  2019-04-25 15:18           1     111
14  2937.0  2019-04-25 15:22           1     106
15  2940.0  2019-04-25 15:37           1      91
16  2942.0  2019-04-25 15:38           1      97
17  2944.0  2019-04-25 15:44           1     106
18  2947.0  2019-04-25 15:47           1     106
19  2949.0  2019-04-25 15:51           1      97

#### Expected outcome:

       ID              time  recordtype glucose
0  2845.0  2019-04-25 00:08           1     109
1  2850.0  2019-04-25 00:50           1        
2  2877.0  2019-04-25 07:02           1     123
3  2881.0  2019-04-25 07:34           1     158
4  2886.0  2019-04-25 08:19           1

<a name='1'></a>
## Part 2: Prepare the data

Check the datatypes of your dataframe. The `glucose` field should be an integer, the `time` field should have a datetime format. If the datatypes are different you should typecast them to the right format.
Make sure that your dataset is sorted by the time column


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<ul><li>use astype() method or pandas.DataFrame.to_datetime() for instance</li>
    <li>make sure that the empty spaces are filled with NaN. Use errors='coerce'</li>
    <li>set_index(), sort_index() and reset_index() are helpful to sort on index</li>
</ul>
</details>

<a name='ex-21'></a>
### Code your solution

In [69]:
# CODE YOUR SOLUTION HERE
import numpy as np


df["ID"] = df["ID"].astype('int64')

df['glucose'] = pd.to_numeric(df['glucose'], errors='coerce')

# df['glucose'] = df['glucose'].astype(pd.Int64Dtype())
# display(df)
#df['glucose'] = df['glucose'].apply(pd.to_numeric, downcast='integer')
# df['glucose'] = df['glucose'].astype('np.int')

# df['ID'] = df['ID'].astype(np.int64)

df['time'] = pd.to_datetime(df['time'])


data_type = df.dtypes
print(data_type)

# set index by time column
df.set_index(['time'],inplace=True)
# df.head(50)


df = df.sort_index()
df.head(10)

ID                     int64
time          datetime64[ns]
recordtype             int64
glucose              float64
dtype: object

                                      ID  recordtype  glucose
time
2019-04-25 00:08:00                 2845           1    109.0
2019-04-25 00:14:00 -9223372036854775808           0      NaN
2019-04-25 00:29:00 -9223372036854775808           0      NaN
2019-04-25 00:44:00 -9223372036854775808           0      NaN
2019-04-25 00:50:00                 2850           1      NaN
2019-04-25 00:59:00 -9223372036854775808           0      NaN
2019-04-25 01:14:00 -9223372036854775808           0      NaN
2019-04-25 01:29:00 -9223372036854775808           0      NaN
2019-04-25 01:44:00 -9223372036854775808           0      NaN
2019-04-25 01:59:00 -9223372036854775808           0      NaN

#### Expected outcome:

ID                     int64
time          datetime64[ns]
recordtype             int64
glucose              float64
dtype: object

<a name='2'></a>
## Part 3: Inspect the data

Now that we prepared the data we are going to inspect the data to get more familiar with the data. You are required to do the following

- inspect the percentage missing data for glucose
- what is the relationship between recordtype and glucose value?
- what is the relationship between ID and glucose value?

Code the solutions to your answers. Create meaningful overviews or statistics

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<ul><li>In the week 01 assignment some functions were explained to inspect missing values</li>
    <li>In the week 01 assignment some functions were explained to groupby value</li>
</ul>
</details>

<a name='ex-31'></a>
### Code your solution

In [70]:
#CODE YOUR SOLUTION HERE

total_data = len(df)
print("Total Data:", str(total_data))

total_missing_values = df.isnull().sum().sum()
print("Total missing data:", str(total_missing_values))

# inspect the percentage missing data for glucose


missing_percentage = df['glucose'].isnull().sum()/ len(df['glucose'])
percentage_missing_glucose = df['glucose'].isnull().sum()*100/ len(df['glucose'])

print('Percentage missing data = {:.3f}'.format(missing_percentage))
print('Percentage missing data = {:.3f} %'.format(percentage_missing_glucose))

# what is the relationship between recordtype and glucose value?
recordtype_glucose_relation = df['recordtype'].corr(df['glucose'])
print(f'The correlation between recordtype and glucose is : {recordtype_glucose_relation}\n')

# what is the relationship between ID and glucose value?
ID_glucose_relation = df['ID'].corr(df['glucose'])
print(f'The correlation between ID and glucose is : {ID_glucose_relation:.2f}\n')

Total Data: 136
Total missing data: 84
Percentage missing data = 0.618
Percentage missing data = 61.765 %
The correlation between recordtype and glucose is : nan

The correlation between ID and glucose is : -0.21

#### Expected outcome percentage missing data
0.6176470588235294

<a name='3'></a>
## Part 4: Interpolate the data

A lot of data is missing. Use interpolation to fill the missing values. Create a new column with the interpolated data. Take an argumentative approach. Select an interpolation method that suits the nature of the data and explain your choice. Mind you that the expected outcome of the interpolation values can differ from the example below

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<ul><li>use Pandas.DataFrame.interpolate() method</li>
</ul>
</details>

<a name='ex-41'></a>
### Code your solution

In [85]:
#CODE YOUR SOLUTION HERE

none_glucose_value = df['glucose'].isnull().sum().sum()
print(f'There are {none_glucose_value} glucose values, should be interpolated.')

df['interpolated'] = df['glucose'].interpolate(method ='time')

# df['interpolated'] = df['glucose'].interpolate(method ='spline', limit_direction= 'forward', order = 5)

# df['interpolated'] = df['glucose'].interpolate(method ='linear', limit_direction='forward', axis=0)
# df['interpolated'] = df['glucose'].interpolate(method ='polynomial', order=2)
# df['interpolated'] = df['glucose'].interpolate(method ='pad', limit=2)

# display(df)
# print(df.interpolate(method ='linear', limit_direction='forward', axis=0) )
# print(df.interpolate(method ='polynomial', order =2) )
# print(df['glucose'].interpolate(method ='time'))
df.head(5)

# interpolation using time is efficient i think because it will take average of glucose value

There are 84 glucose values, should be interpolated.

,ID,recordtype,glucose,interpolated,rolling_mean
time,,,,,
2019-04-25 00:08:00,2845,1,109.0,109.000000,NaN
2019-04-25 00:14:00,-9223372036854775808,0,NaN,9.013809,109.101449
2019-04-25 00:29:00,-9223372036854775808,0,NaN,-207.387457,109.456522
2019-04-25 00:44:00,-9223372036854775808,0,NaN,-379.961812,109.963768
2019-04-25 00:50:00,2850,1,NaN,-437.822434,110.318841

#### Example outcome

                 time                   ID  recordtype  glucose  interpolated
0 2019-04-25 00:08:00                 2845           1    109.0    109.000000
1 2019-04-25 00:14:00 -9223372036854775808           0      NaN    109.466667
2 2019-04-25 00:29:00 -9223372036854775808           0      NaN    109.933333
3 2019-04-25 00:44:00 -9223372036854775808           0      NaN    110.400000
4 2019-04-25 00:50:00                 2850           1      NaN    110.866667

<a name='4'></a>
## Part 5: Plot the data

Create a plot with the original data and the interpolated data. Consider what the best representation is for visualisation of actual values and modelled/imputed values. An example of such a plot is given below. This plot however is not considered the best practice. 

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>
<ul><li>figure(x_axis_type='datetime') automatically makes nices labels of the datetime data</li>
</ul>
</details>

<a name='ex-51'></a>
### Code your solution

In [72]:
from bokeh.io import output_notebook
from bokeh.plotting import figure, output_file, show
from bokeh.layouts import gridplot
from bokeh.io import output_notebook
from bokeh.plotting import ColumnDataSource
output_notebook()

In [86]:
#CODE YOUR SOLUTION HERE



# source = ColumnDataSource(df)
ColumnDataSource = df.copy()
fig = figure(x_axis_type = 'datetime', title = 'A plot with the original data and the interpolated data', 
             plot_height = 400, plot_width = 600, x_axis_label = "Time", y_axis_label = "Glucose/Interpolated")
fig.line(x = ColumnDataSource.index, y = ColumnDataSource['glucose'], line_width=6, color = "blue")
fig.line(x = ColumnDataSource.index, y = ColumnDataSource['interpolated'], line_width=2, color = "red")
show(fig)

<a name='6'></a>
## Part 6: Challenge

It might even be interesting to introduce a widget in which you can select different methods to interpolate.
1. Can you improve the interpolation by choosing an other method?
2. Can you add an rolling mean line? 
2. Can you improve the plot by making it interactive?

<a name='ex-61'></a>
### Code your solution

In [74]:
#CODE YOUR SOLUTION HERE

import numpy as np

df['rolling_mean'] = df['interpolated'].rolling(window=2).mean()
df.head()

,ID,recordtype,glucose,interpolated,rolling_mean
time,,,,,
2019-04-25 00:08:00,2845,1,109.0,109.000000,NaN
2019-04-25 00:14:00,-9223372036854775808,0,NaN,109.202899,109.101449
2019-04-25 00:29:00,-9223372036854775808,0,NaN,109.710145,109.456522
2019-04-25 00:44:00,-9223372036854775808,0,NaN,110.217391,109.963768
2019-04-25 00:50:00,2850,1,NaN,110.420290,110.318841